---
- name: set docker_portainer_volume
  set_fact: docker_portainer_volume="{{docker_portainer_container_volume_base}}/{{docker_portainer_container_name}}-{{docker_portainer_version}}"

- name: create volume directory for data
  file: path={{docker_portainer_volume}}/data state=directory recurse=yes

- name: install container
  docker_container:
    name: "{{docker_portainer_container_name}}"
    image: "portainer/portainer:{{docker_portainer_version}}"
    state: "{{docker_portainer_state}}"
    volumes:
      - "{{docker_portainer_volume}}/data:/data"
    ports:
      - "{{docker_portainer_port}}:9000"